# -*- coding: utf-8 -*-
"""Real-Time Object Tracking with YOLOv5 + Deep SORT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKYgrwW1BbCxeOcU-7lO2w31ebT7-_yO
"""

# object_tracking_yolo_sort.py

import cv2
import torch

# Load YOLOv5
def load_yolo_model():
    model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
    model.conf = 0.4
    return model

# Load Deep SORT dependencies
from deep_sort_realtime.deepsort_tracker import DeepSort

def main():
    model = load_yolo_model()
    deepsort = DeepSort(max_age=30)

    cap = cv2.VideoCapture("test_video.mp4")  # Use 0 for webcam

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # Inference
        results = model(frame)
        detections = results.xyxy[0].cpu().numpy()

        # Parse YOLO detections
        yolo_detections = []
        for *box, conf, cls in detections:
            x1, y1, x2, y2 = box
            yolo_detections.append(([int(x1), int(y1), int(x2 - x1), int(y2 - y1)], conf, int(cls)))

        # Track using Deep SORT
        tracks = deepsort.update_tracks(yolo_detections, frame=frame)

        for track in tracks:
            if not track.is_confirmed():
                continue
            track_id = track.track_id
            l, t, w, h = track.to_ltrb()
            cv2.rectangle(frame, (int(l), int(t)), (int(l + w), int(t + h)), (0, 255, 0), 2)
            cv2.putText(frame, f'ID: {track_id}', (int(l), int(t) - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

        cv2.imshow("Real-Time Object Tracking", frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    main()